### PR TITLE
Validation Code tag microsoft-academic-services

### PR DESCRIPTION
**Pull request by TimShererWithAquent**
[1907184](https://dev.azure.com/mseng/TechnicalContent/_workitems/edit/1907184)

### CODE REVIEW

**Comment by TimShererWithAquent** [comment]
@dbradish-microsoft This is ready for review - and very short.

**Comment by TimShererWithAquent** [comment]
@v-andreaco I looked for the owner of this repo, but the lookup found no names associated with it.

**Comment by dbradish-microsoft** [comment]
#sign-off

**Comment by v-andreaco** [comment]
@DarrinEide 

Docs Portal is suggesting that you're the owner of this repo. When you get a chance, would you please review the change and merge if you approve?

**Review by RickRogahn — APPROVED** [review]

**Comment by RickRogahn** [comment]
I believe @***@***.***> is on vacation at the moment.  Approved and merged.
________________________________

**Pull request merged**
